### ISSUE TITLE
Task Tracker

### ISSUE THREAD

**Issue by G6LAW** [G6LAW/ADDA-System#1]
# TASK MANAGER:

### Task Planner
- [x] Organize Info.
- [x] Organize Global Tasks.
- [x] Organize DASHBOARD Tasks.
- [ ] Organize PROJECTS Tasks.
- [ ] Organize CONTACTS Tasks.
- [ ] Organize MUS1K Tasks.
- [ ] Organize BIBLIO Tasks.
- [ ] Organize MANAGER Tasks.
- [ ] Organize CLASSES Tasks.
- [ ] Organize FINANCE Tasks.

## Info
>ADDA System is a web based creation to help personal and professional improvement. 
>It must be acessible from web-browsers and in the future from Apps. It have modules from different areas, 
>The main modules are:
>    * DASHBOARD: Use to see summaries of other modules, as acess them.
>    * PROJECTS: Manage projects classified by classes PE, AR, ES, IT and ED; and specific areas. 
>    * CONTACTS: Assign contacts from google and connect them in projects. More information than google's are avaliable here.
>    * MUS1K: Padronize and organize music sheets, creating chords in letters and being able to advise about progressions. It also exports MIDI files.
>    * BIBLIO: Keep in track all the readings, with tags, plannings and right metadata. Also, is the main page of raw files from projects. (oogle Drive Based)
>    * MANAGER: Time consuming and organizer to keep projects, tasks, readings and else organized. It uses google calendar as interface but have more layers of configurations.
>    * CLASSES: System to organize students and track their progress. (will be avaiable for users in the future)
>    * FINANCE: Keep track of financial stuff, paying bills and Stocks.
