### ISSUE TITLE
Module | DASHBOARD

### ISSUE THREAD

**Issue by G6LAW** [G6LAW/ADDA-System#3]
#### Full Description:
>DASHBOARD is the main window of the system. It is responsible by loggin in the User, establishing connection with the database, _google and other network connections as instagram and twitter._ [^1] 
>It have also a center table in wich is shown all the modules. All The global configurations are set in this window. 

#### Tasks:
- [ ] Planning
    - [ ] Organize Existing Content
    - [ ] Create folder Structure (and files)
    - [ ] Create DEV MongoDB.
    - [ ] Create User Object Abstraction
    - [ ] Document DB Requests
    - [ ] Express
    - [ ] Handlebars
    - [ ] MiddleWare
    - [ ] ~Google API~[^1]
- [ ] Back-End
    - [ ] Mongoose
    - [ ] Create User
    - [ ] Config Sessions
    - [ ] Validating user
    - [ ] Passport
    - [ ] User limits
    - [ ] Set Modules info.json file
    - [ ] ModulesFinder()

- [ ] Front-End
    - [ ] Navbar
    - [ ] Footer 
    - [ ] New User Form
    - [ ] Login Form
    - [ ] Config Form
    - [ ] Dinamic Modules Table
    - [ ] ~Calendar Table~[^1]
    - [ ] ~Modules Resume infos~[^1]

- [ ] Front-End (Mobile)
    - [ ] Navbar
    - [ ] Footer 
    - [ ] New User Form
    - [ ] Login Form
    - [ ] Config Form
    - [ ] Dinamic Modules Table
    - [ ] ~Calendar Table~[^1]
    - [ ] ~Modules Resume infos~[^1]
---

[^1]: Next Version.
